class Customer < ActiveRecord::Base
  attr_accessible :customer_id, :first_name, :group_flag, :group_id, :identity_code, :identity_kind
  establish_connection "remote_db"
  set_table_name "BB_CUSTOMER_INFO_T"
  set_primary_key :customer_id
  ignore_table_columns :city_code,
                       :region_code,
                       :belong_code,
                       :credit_control,
                       :customer_level,
                       :customer_kind,
                       :customer_type,
                       :service_level,
                       :secrecy_level,
                       :hcust_flag,
                       :industry_code,
                       :country_code,
                       :cust_name_alias,
                       :create_date,
                       :serving_status,
                       :unit_count,
                       :special_credit,
                       :customer_grade,
                       :developer_dealer,
                       :belong_dealer,
                       :active_date,
                       :modify_date,
                       :logout_date,
                       :cust_leave_word,
                       :brand_ind,
                       :brand_org,
                       :customer_group_id,
                       :customer_value,
                       :busi_customer,
                       :section_kind,
                       :first_market,
                       :second_market,
                       :third_market,
                       :first_industry,
                       :second_industry,
                       :third_industry,
                       :span_section,
                       :preserve01,
                       :preserve02,
                       :preserve03,
                       :preserve04,
                       :preserve05
  has_many :service_relations, :foreign_key => "customer_id"
end
